stages:
  - CheckSonar
  - CheckPhpcs
  - Deploy

.CheckSonarqube: &CheckSonarqube |
  if [[ $CI_PROJECT_URL = *"rmt2/server"* ]] && [ "$CI_COMMIT_REF_NAME" = "develop" ]; then
    sonar-scanner -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME -Dsonar.gitlab.project_id=$CI_PROJECT_ID -Dsonar.gitlab.user_token=$USER_TOKEN -Dsonar.login=$SONAR_KEY
  else
    sonar-scanner -Dsonar.analysis.mode=preview -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME -Dsonar.gitlab.project_id=$CI_PROJECT_ID -Dsonar.gitlab.user_token=$USER_TOKEN -Dsonar.login=$SONAR_KEY
  fi

.PhpcsScan: &PhpcsScan |
  pushComment(){
      curl --request POST --header "PRIVATE-TOKEN: $USER_TOKEN" \
      --form "note=$OUTPUT" --form "path=dudeism.md" \
      --form "line=1" --form "line_type=new" \
      https://git.hblab.vn/api/v4/projects/$CI_PROJECT_ID/repository/commits/$CI_COMMIT_SHA/comments
      echo $OUTPUT
      exit 1
  }
  
  OUTPUT=$(phpcs --standard=PSR2 app/) || pushComment


Sonar:
  stage: CheckSonar
  image: khainguyendinh/sonar-scanner
  
  script:
    - *CheckSonarqube
    
Phpcs:
  stage: CheckPhpcs
  image: composer
  script:
    - curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar && curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcbf.phar
    - mv phpcs.phar /usr/local/bin/phpcs && chmod +x /usr/local/bin/phpcs
    - mv phpcbf.phar /usr/local/bin/phpcbf && chmod +x /usr/local/bin/phpcbf
    - *PhpcsScan

DeployTest:
  stage: Deploy
  image: composer
  only:
    - develop@rmt2/server
  script:
    - apk add rsync
    - mkdir -p ~/.ssh
    - ssh-keyscan -H '54.238.131.165'  >> ~/.ssh/known_hosts
    - echo "$DEPLOY_SERVER_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 400 ~/.ssh/id_rsa
    - composer global require hirak/prestissimo
    - composer install --no-dev
    - php artisan apidoc:generate
    - rsync --progress -avzh --exclude='.git' --exclude='public/img' --exclude='public/svg' --exclude='public/js' --exclude='public/css' -e "ssh -i ~/.ssh/id_rsa" --rsync-path="sudo rsync" . ubuntu@54.238.131.165:/var/www/html/rmtServer
